# Change these first
owner: felipesotero # Your GitHub organization or username, where this repository lives
repo: upptime-navega # The name of this repository

sites:
  - name: Navega Home
    url: https://navega.tech
    headers:
      User-Agent: "UpptimeMonitor"
  - name: Navega n8n
    url: https://n8n.navega.tech
    headers:
      User-Agent: "UpptimeMonitor"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime-navega
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Navega - Monitoramento
  introTitle: "Monitoramento dos sites da Navega"
  introMessage: Bem-vindo ao Upptime da Navega
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
